kumuluzee:
  name: games-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  discovery:
      etcd:
        hosts: http://192.168.99.100:2370
      ttl: 30
      ping-interval: 20

rest-config:
  string-property: Monday
  boolean-property: true
  integer-property: 23